### PR TITLE
Added virtual ValueEquals method

### PR DESCRIPTION
**Pull request by khellang**
This will allow you to easily do custom equality checking on value, like this

```csharp
public abstract class StringEnumeration<TEnumeration> : Enumeration<TEnumeration, string>
    where TEnumeration : StringEnumeration<TEnumeration>
{
    protected StringEnumeration(string value, string displayName, StringComparison comparison)
        : base(value, displayName)
    {
        Comparison = comparison;
    }

    public StringComparison Comparison { get; private set; }

    protected override bool ValueEquals(string value)
    {
        return Value.Equals(value, Comparison);
    }
}
```

Notice the `StringComparison` constructor argument. This will allow you to do culture/casing customization of string value comparison.

### CODE REVIEW

**Comment by khellang** [comment]
Any chance this could make it in?

**Comment by ChrisMissal** [comment]
@khellang can you talk about the use case for this? Are you wanting to have different types of StringEnumeration and they're going to need different StringComparisons? I just don't want to say yes or no without fully understanding the whole picture.

**Comment by khellang** [comment]
Yes, but not limited to. I just want a way to customize value equality checking. How can I do that today?

**Comment by khellang** [comment]
Thanks! :+1:

**Pull request merged**
